; PlatformIO Project Configuration - ESP32 Mitsubishi AC IR Controller
;
;   aircon-esp32   → src/aircon/main.cpp（ESP32 IR 空调控制）

[env:aircon-esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = -<*> +<aircon/>

; --- 首次烧录：取消注释 usb 两行，注释 ota 两行 ---
;upload_protocol = esptool
;upload_port = /dev/ttyUSB0
upload_protocol = espota
upload_port = esp32-device-name.local
;monitor_port = /dev/ttyUSB0
;monitor_speed = 115200
upload_speed = 921600

lib_deps =
    crankyoldgit/IRremoteESP8266@^2.8.5
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson

build_flags =
    -DMQTT_MAX_PACKET_SIZE=2048
